### ISSUE TITLE
Text mode is in an overlay

### ISSUE THREAD

**Issue by joyously** [ClassicPress-research/ClassicPress-Editor#11]
The text mode needs to be the same interface as before. Some of us use it exclusively.
But the v5 editor uses an overlay for text mode, also for entering code by clicking on the button with `{;}` on it.
It not only disallows using other parts of the page, but it's hidden under the admin menu. Also, it positions you at the bottom of the content.

This is the old editor:
![Edit Page ‹ Classicly Pressed — ClassicPress-02](https://user-images.githubusercontent.com/7957680/131275575-e7d1e77a-f868-44f0-a71a-3c45cbafdb7b.jpg)

And this is the new one:
![Edit Page ‹ Classicly Pressed — ClassicPress-34](https://user-images.githubusercontent.com/7957680/131275598-3bff801e-70d9-4c4e-a1fb-859ef7fd7a22.jpg)

**Comment by johnalarcon** [comment]
This is implemented using a "panel" dialog (meaning: an overlay). I'm not finding a way to disable the overlay. This plugin may need to be rewritten to, say, swap a hidden text area in/out of view when the source/WYSIWYG views are toggled.

**Comment by arjayarana** [comment]
Hi guys. I've decided to pitch in.

I will add that the overlay window is much too large for an ordinary laptop screen. My resolution is 1366 x 768.
 
![source-code-window](https://user-images.githubusercontent.com/89768197/131303812-fd3d5637-24a4-4d26-8635-aaeffe1c96d3.png)

**Comment by johnalarcon** [comment]
The overlay seems to work for some and not others. In my Firefox, it renders properly. Notably, I think the overlay will have to be removed and this functionality reimplemented in a way that doesn't "block" the rest of the page.

**Comment by johnalarcon** [comment]
While I did want to solve this, I've spent a few hours on this today and am no closer to a solution. If someone else has ideas or code, please jump in. Personally, I'm fine with text mode being an overlay and probably won't revisit this issue.

**Comment by joyously** [comment]
If you look at my PR #29 you'll see the Text mode works great as it always did. All that's missing is the Visual toolbar, for some reason. (and I think I made some progress on that by generating a new skin for v5 called lightgray, which is what core loads by default but it's not in the PR).

**Comment by johnalarcon** [comment]
I saw it was in draft status, so, I didn't take a look. I'll give it a go today.

**Comment by johnalarcon** [comment]
I'm seeing an error in the console when clicking back and forth between the visual and text tabs. Click back and forth between the tabs a couple times to reproduce. It looks like the missing function may be crashing the script.

>Uncaught TypeError: c.theme.resizeTo is not a function
>in https://site/wp-content/plugins/classicpress-editor/js/tinymce/wp-tinymce.php?c=1&ver=591-20210827:9

**Comment by joyously** [comment]
Yes, I've been working on that. The core script editor-expand.js calls a function from the modern theme. The silver theme does not have this. I'm patching it, among other things. I am close.

**Comment by joyously** [comment]
Fixed by #29

**Comment by johnalarcon** [comment]
This is fixed on main. The text mode is no longer pushed into an overlay and maintains the traditional text mode experience. Thanks, Joy!
