### ISSUE TITLE
Warning message every time I exit

### ISSUE THREAD

**Issue by simplycomputing** [ClassicPress-research/ClassicPress-Editor#12]
I get this warning message every time I try to navigate away from the page. This is even after making no changes, and also after saving the page.

![warning](https://user-images.githubusercontent.com/46998578/131280365-0e65310e-6452-4ae2-aacd-6cad35e8f64d.jpg)

**Comment by johnalarcon** [comment]
I was getting that, too...and unable to figure out what I'd changed to warrant it. I expect we'll have a lot of little things to discover and fix along the way. :)

**Comment by johnalarcon** [comment]
This is a known issue and it looks like there may already be code to resolve it. I haven't tried the fix; just doing the research. See this thread, [comment 28](https://core.trac.wordpress.org/ticket/52440#comment:28).

**Comment by johnalarcon** [comment]
Also related: https://www.searchenginejournal.com/wordpress-5-6-1-bug/395653/

**Comment by simplycomputing** [comment]
I tried the standalone fix in functions.php and it made no difference to me.

**Comment by johnalarcon** [comment]
I applied the standalone fix and it seems to partially work. That is, if you leave the page, it doesn't prompt you unless you changed something in the editor. Unfortunately, even just clicking into the editor is registering as a change, so, clicking in the editor will still pop that dialog. This partial fix is on the main branch.

**Comment by johnalarcon** [comment]
Can you test the `main` branch to see if this behavior improved at all?

**Comment by simplycomputing** [comment]
Nope, not seeing any difference yet. I think I'm testing main branch.

**Comment by simplycomputing** [comment]
I had to test this through GitHub desktop because when I click download zip nothing happens.

So it could well be that I am not getting the latest version.

**Comment by johnalarcon** [comment]
Weird. I tried the download and it seems ok right now.

Possibly related: I noticed some strange behavior on GitHub yesterday where the repo's nav tabs were showing one number for open issues and the open issues page was showing a different number. Also, I had several GitHub commits fail yesterday, even though they successfully went through on my end, they never showed up here.

I bet Microsoft is developing right against the live site. 😱

**Comment by simplycomputing** [comment]
I closed the browser and tried again. Works now. The download that is... sadly not the fix. Still the same.

**Comment by johnalarcon** [comment]
Did you try it in alternate browsers? On this end, it's a partial fix. I'm using Firefox. If I visit the post edit screen and _do not click the editor_, I can exit without a prompt. If I do click the editor, then I am prompted when I try to leave. Can you verify that this is not happening for you?

**Comment by simplycomputing** [comment]
Ah, interesting. I have been testing this on _pages_ since I very rarely use posts. 

It does work on **posts** for me. Not on **pages**.

**Comment by johnalarcon** [comment]
Aha! A clue! :) I'll take a closer look when I dig back in.

**Comment by simplycomputing** [comment]
OK, this is weird. I got annoyed with that message so I deactivated your plugin. I was still getting the message when I go to a page or post and try and navigate away. So I deleted the plugin. _Still getting the message._ 

Further investigation shows me that is doesn't always happen, only with pages that I worked on or created with the new editor.

OK, so I reinstalled the editor to test this further. But now if I create a new page or post it no longer gives me that message - works perfectly. But the older ones still do.

I don't know if you can make any sense of this. I haven't got any idea, but thought it was worth reporting.

**Comment by johnalarcon** [comment]
That's interesting. Thanks for reporting.

What happens if you open one of the old (problematic) posts and _save_ it in the new editor? Can you then exit that post's edit screen (on the next load) without it causing issues?

**Comment by simplycomputing** [comment]
Nope. If I go to one of the old pages, make a change, hit update and then view page then I still get the warning.

**Comment by simplycomputing** [comment]
No, it's all over the place. I create a page, hit **publish** and then view page and it goes straight to the page. I go back and make an edit, hit **update** and it then starts to give me the warning.

**Comment by johnalarcon** [comment]
Ok.

My thought is that it has to do with the Tiny `autosave` plugin. Take a look at [this line](https://github.com/ClassicPress-research/ClassicPress-Editor/blob/5d534aa0db9d11c1adbee3a1bcd7d14b8bff3bf7/scripts/classicpress-editor.js#L17) and remove the `autosave` from it. Just below it, you'll see several other autosave-related config options; comment them out. Then recheck.

It also couldn't hurt to clear the browser cache.

**Comment by simplycomputing** [comment]
Nope, didn't help. And I moved to a different browser. I'll try FF.

**Comment by simplycomputing** [comment]
So is the the fix you are trying for this?
https://core.trac.wordpress.org/ticket/52038

**Comment by johnalarcon** [comment]
Sounds related. In the case of the post edit screen, though, the editor is not in the Excerpt field. The comments make me think they didn't actually fix it.

**Comment by simplycomputing** [comment]
Yes, seems like its a problem that keeps popping up. And this seems to be a common theme: 

> the issue seems to be intermittent – it’s really hard to pin down why it happens some times and not others!

and also this:

> it only happens, when it happens, in older pages or posts

**Comment by joyously** [comment]
@simplycomputing I don't experience this issue. Can you try with the latest version?
I read the main ticket over at WP and it seems that they had added changes we don't have, and then tried to fix those changes. They also have a different version of jQuery which was mentioned in other tickets as behaving differently with regard to loading, and it manifested on the editor page.
So I really don't think their "fix" would apply here. The current version of this plugin is fairly different from when you wrote this issue.

**Comment by simplycomputing** [comment]
Just downloaded the latest code and installed. It still does it for me on _existing_ pages, but if I create a _new_ page it is fine.

Is there any "setting" or some value that is stored with the page that could be triggering this?

**Comment by simplycomputing** [comment]
OK - I have another clue. On  pages that still do it, if I make a change and hit update it still does it. But if make a second change and update, then it is fixed. Works fine thereafter.

So maybe something associated with autosave or revisions?

**Comment by simplycomputing** [comment]
You don't even need to make a change. 
1. Open page
2. Try to view and get message
3. Cancel leaving and update page
4. Try to leave and get message
5. Cancel leaving and update page
6. Try to view... no message!

**Comment by joyously** [comment]
Is this with the same pages that you tested originally, or different pages?
Is this with Chrome or Firefox? (the WP ticket said it was different)
I never got this error, so I don't know how to debug it. Thanks for testing.

**Comment by simplycomputing** [comment]
Same pages I tested originally I think. I have been mostly working with stuff on the first page of my pages table so will do some testing deeper in.

I am using Brave.

**Comment by simplycomputing** [comment]
I tried it in some pages I definitely haven't looked at for a while. On these you only need _one_ update to clear it, ie
1. Open page
2. Try to leave and get message
3. Cancel leaving and update page
4. Try to view... no message!

**Comment by simplycomputing** [comment]
OK - I tried installing this on a completely different site using FF. It doesn't do it at all. Everything works correctly.

**Comment by simplycomputing** [comment]
And that site is good with Brave too. Looks like it is some localised thing with my initial site, maybe remnant of testing previous versions?

Since I can't reproduce this either on a new site I think you can close it.

**Comment by joyously** [comment]
OK, thanks.
We can reopen this if it pops up again.
