### ISSUE TITLE
"Disable the visual editor when writing" option has no effect

### ISSUE THREAD

**Issue by viktorix** [ClassicPress-research/ClassicPress-Editor#16]
When trying to disable visual editor in user profile options, it has no effect on the new v5 editor.

**Comment by johnalarcon** [comment]
Thanks for the report. The editor isn't connected to any admin or user options at this time. This will be implemented before release.

**Comment by joyously** [comment]
Please test with the latest version and close the issue if fixed.

**Comment by johnalarcon** [comment]
This is fixed on `main`. Thanks, Joy!
