### ISSUE TITLE
Editor is enabled on the comment edit screen

### ISSUE THREAD

**Issue by viktorix** [ClassicPress-research/ClassicPress-Editor#17]
It shouldn't be enabled, but it is right now.

![image](https://user-images.githubusercontent.com/1692600/131284075-2fb13d27-b2ec-4524-8862-4b141439e034.png)

**Comment by johnalarcon** [comment]
Actually, this should be configurable. Some users (me, for example) like to use the advanced editor in comments. There's various contexts where the editor can be used – widgets, excerpts, taxonomy descriptions, etc. these will probably end up being admin settings allowing each user to decide the enabled contexts.

**Comment by arjayarana** [comment]
I will add that the editor is also enabled in Quick Draft (dashboard widget)

![quick-draft](https://user-images.githubusercontent.com/89768197/131312508-88a568a2-9f74-4227-9beb-c85c62453b04.png)

**Comment by johnalarcon** [comment]
> There's various contexts where the editor can be used – widgets, excerpts, taxonomy descriptions, etc.

Note the "etc" part. :)
