### ISSUE TITLE
Other plugins seem able to integrate

### ISSUE THREAD

**Issue by arjayarana** [ClassicPress-research/ClassicPress-Editor#19]
Hi guys. I've decided to pitch in.

I have Shortcodes Ultimate from WP installed, and it seems to work with this editor. I've tested one shortcode, Note (the paragraph in yellowish background), and it works.

![shortcodes1](https://user-images.githubusercontent.com/89768197/131306727-60263ff4-57ca-4972-a780-6a8b495c0852.png)

![shortcodes2](https://user-images.githubusercontent.com/89768197/131306759-3d285bac-7e9a-48a0-ba23-7f8320461956.png)

![shortcodes3](https://user-images.githubusercontent.com/89768197/131306781-4e7b2287-8dc9-4dae-a302-600fbbed9fe8.png)

**Comment by johnalarcon** [comment]
Thanks. That plugin doesn't actually interface with the editor (note that it and the Add Media button are _outside_ the editor . ;) Closing this as it's a success report rather than an issue.
