### ISSUE TITLE
No button to insert "Read More" tag

### ISSUE THREAD

**Issue by arjayarana** [ClassicPress-research/ClassicPress-Editor#21]
There's no button to insert the code `<!--more-->` that will break the post in the archive pages. Maybe this was WordPress-specific.

**Comment by joyously** [comment]
This is part of the `wordpress` JS plugin for TinyMCE, mentioned in issue #2

**Comment by johnalarcon** [comment]
Thanks for reporting. We'll have a lot of little things to think about (and figure out!) and every report helps to keep everyone on the same page with outstanding items and progress.

**Comment by striebwj** [comment]
Let's consolidate these into a single issue, let's move to #2
