### ISSUE TITLE
Preview window is much too large, overlapped by menu

### ISSUE THREAD

**Issue by arjayarana** [ClassicPress-research/ClassicPress-Editor#22]
This is similar to issue #3 and issue #11 

The preview window is much too large for an ordinary screen, which is what I use (resolution: 1366 x 768). It is also overlapped by the sidebar menu.

![preview-window](https://user-images.githubusercontent.com/89768197/131477817-6d000f15-24bf-4589-8766-8bc6f5379b45.png)

**Comment by striebwj** [comment]
Lets's consolidate these into a single issue we can track.
