### ISSUE TITLE
"Visual aids" seem to be not functioning

### ISSUE THREAD

**Issue by arjayarana** [ClassicPress-research/ClassicPress-Editor#24]
"Visual aids" under the View Menu does not seem to be functioning. I can't see any difference whether it's toggled or not. I thought maybe it has something to do with tables, but it also makes no difference to the table I've created.

Note: I never used this function before, and so I don't exactly know what it does.

**Comment by johnalarcon** [comment]
If you're not sure how something is supposed to work, how can you know if it's not working? ;)

Closing this as it's not actionable.
