### ISSUE TITLE
Implement plugin - fullscreen

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#34]
### Implement `fullscreen` TinyMCE plugin

The various controls and behaviors of the v4 plugin currently included in ClassicPress should be reasonably replicated by the v5 editor, or by the updated TinyMCE core. Prior to testing, install the [ClassicPress Editor](https://github.com/ClassicPress-research/ClassicPress-Editor/archive/refs/heads/main.zip) plugin. **Do not activate it.** If the plugin is already installed, be sure to deactivate it before starting your tests.

#### Testing Notes
```
1. Activate the new Classic Editor plugin.
2. Click to edit any post with the built-in editor.
3. Click to view the editor in fullscreen mode.
4. Add some content to the editor.
5. Minimize the editor.
6. Verify that the editor content is accurate and the view is not obscured.
```

This issue has a corresponding item on the Task List in issue #2.

**Comment by joyously** [comment]
I put some patch CSS into my PR because they changed the names of the fullscreen button.
Old one uses `mce` prefix and new one uses `tox` prefix. 
This could have changed for other things that the core plugins interact with.

**Comment by johnalarcon** [comment]
Thanks, Joy. I suspect ithey changed a whole slew (if not all) of the classes as the easiest way to avoid conflicts.

**Comment by joyously** [comment]
### Testing Notes
The behavior in 4.x for the post edit page is
- fullscreen mode is not on the toolbar, but accessed by the shortcut toggle Ctrl-Shift F
- fullscreen mode is only in Visual mode, and your cursor has to be in the content
- regardless of screen size and distraction-free mode, fullscreen puts the toolbar at the top of the window and uses the entire window for the content
- fullscreen mode hides the distraction-free mode button, but it should be unaffected (set to its previous value) when you get out of fullscreen mode
For 4.x on the Text Widget (which was added much later), the fullscreen shortcut key works, but the toolbar is hidden under the admin bar and admin menu. I suppose 5.x should not duplicate that.

**Comment by joyously** [comment]
There is code in the editor setup
```
	if ( ! wp_is_mobile() ) {
		if ( $set['_content_editor_dfw'] ) {
			$mce_buttons[] = 'dfw';
		} else {
			$mce_buttons[] = 'fullscreen';
		}
	}
```
so it seems like you would get either the fullscreen button or the distraction free writing button, but in my tests of 4.x, I never see the fullscreen button.
Can someone verify this? Otherwise, I think this is working as 4.x is (no fullscreen button, but shortcut key works, even in Text Widget).

**Comment by joyously** [comment]
When testing today, the Text widget in full screen has the admin bar and admin menu visible. I thought it wasn't, as referenced above, but I checked out the code from back then and it looks the same. I'm not sure I understand that except that the styles aren't written to handle the widget page.

**Comment by joyously** [comment]
Trying this again with 4.x, the admin menu and admin bar overlap the editor in full screen mode, and the full screen button is not on the toolbar regardless of the full height Screen Option. So I'm going to call this done.
