### ISSUE TITLE
Implement plugin - link

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#37]
### Implement `link` TinyMCE plugin

The various controls and behaviors of the v4 plugin currently included in ClassicPress should be reasonably replicated by the v5 editor, or by the updated TinyMCE core. Prior to testing, install the [ClassicPress Editor](https://github.com/ClassicPress-research/ClassicPress-Editor/archive/refs/heads/main.zip) plugin. **Do not activate it.** If the plugin is already installed, be sure to deactivate it before starting your tests.

#### Testing Notes
```
1. Click to edit any post with the built-in editor.
2. Add the element being tested to the post body using the relevant editor button/menu.
3. Save the post.
4. Activate the new Classic Editor plugin.
5. Click to edit the same post.
6. Verify that the new editor replicates the expected behavior.
```

This issue has a corresponding item on the Task List in issue #2.

**Comment by joyously** [comment]
This one is questionable, because the v4 did not use it. It instead used wplink which incorporates the lookup and search for posts.
But wplink has a call to a part of the JS (editor.ui.*) that was removed in v5.

**Comment by johnalarcon** [comment]
Agree. I figure a couple/few of these plugins may not need to necessarily be ported, while others may take a complete rewrite. I've included it here for completeness.

**Comment by joyously** [comment]
Nothing to do here since this plugin is only a fallback for when `wplink` is missing.
We have the 5.10 version with the security fix.
