### ISSUE TITLE
Implement plugin - tabfocus

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#41]
### Implement `tabfocus` TinyMCE plugin

The various controls and behaviors of the v4 plugin currently included in ClassicPress should be reasonably replicated by the v5 editor, or by the updated TinyMCE core. Prior to testing, install the [ClassicPress Editor](https://github.com/ClassicPress-research/ClassicPress-Editor/archive/refs/heads/main.zip) plugin. **Do not activate it.** If the plugin is already installed, be sure to deactivate it before starting your tests.

#### Testing Notes
```
Add testing notes here.
```

This issue has a corresponding item on the Task List in issue #2.

**Comment by viktorix** [comment]
I tested 1.0.17-alpha. I can't tab into toolbar. It goes from title to editor text area, and then moves on. Tabbing backward does catch text tab. Here's a Loom of the test, no audio:
https://www.loom.com/share/579950af9bfb407d9421a7db789ed4c2

**Comment by joyously** [comment]
That's what I get also, but what _should_ it do? The 4.x version seems to be about the same.

**Comment by viktorix** [comment]
Actually, I don't think there is anything else left to do here. Doing a little research on this, tabfocus plugin simply allows us to tab between the editor and the element we specify.

The actual TinyMCE accessibility is already built-in and has specific shortcuts:
https://www.tiny.cloud/docs/advanced/accessibility/

So we can't tab into toolbar. We use ALT+F10 to focus on it and arrow keys to navigate.

For reference, from that page:

>To focus on the editor toolbars, press Alt+F10; which moves the keyboard focus to the first toolbar button on the first toolbar. To move between toolbar buttons within toolbar groups (visual groups of toolbar buttons), use the Left Arrow and Right Arrow keys. To move the focus between toolbar groups, use the Tab or Shift+Tab keys. When you reach the end of a toolbar group the Right Arrow key will return the focus to the start of the toolbar group. To activate or select the highlighted toolbar button, use the Enter, Return, or Spacebar keys. To return focus to the content area from the toolbar, use the Esc key.

I think this issue is done, basically. Keyboard navigation does work in v5.

**Comment by joyously** [comment]
I think that's pretty much the same as the [4.x docs](https://www.tiny.cloud/docs-4x/advanced/keyboard-shortcuts/)

> 
> Focus to menubar | Alt+F9
> Focus to toolbar | Alt+F10
> Focus to element path | Alt+F11 
> Focus to contextual toolbar | Ctrl+Shift+E > Ctrl+Shift+P
> 
> Execute command | Enter / Space
> Focus next widget | Right Arrow / Tab / Down Arrow
> Focus previous widget | Left Arrow / Shift+Tab / Up Arrow
> Open widget menu | Down Arrow
> Open submenu | Left Arrow
> Close submenu | Right Arrow
> Close dialog | Esc
> Close menu | Esc
> Move focus back to editor body | Esc
> 


Our Help text says
```
Focus shortcuts:

Alt + F8 | Inline toolbar (when an image, link or preview is selected)
Alt + F9 | Editor menu (when enabled)
Alt + F10 | Editor toolbar
Alt + F11 | Elements path

To move focus to other buttons use Tab or the arrow keys. 
To return focus to the editor press Escape or use one of the buttons
```
so if that needs fixing it belongs in #43.
