### ISSUE TITLE
Implement plugin - textcolor

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#42]
### Implement `textcolor` TinyMCE plugin

The various controls and behaviors of the v4 plugin currently included in ClassicPress should be reasonably replicated by the v5 editor, or by the updated TinyMCE core. Prior to testing, install the [ClassicPress Editor](https://github.com/ClassicPress-research/ClassicPress-Editor/archive/refs/heads/main.zip) plugin. **Do not activate it.** If the plugin is already installed, be sure to deactivate it before starting your tests.

#### Testing Notes
```
Add testing notes here.
```

This issue has a corresponding item on the Task List in issue #2.

**Comment by johnalarcon** [comment]
In v4, the textcolor plugin allows for adding color to text. When a color is selected, that color remains the active color which can then be applied to other text elements with a click. This functionality replicated in v5.

**Comment by joyously** [comment]
When I use the default core configuration (as in my PR), I get
`Text color plugin is now built in to the core editor, please remove it from your editor configuration`
That's why I removed it.
I didn't understand why the v5 download comes with that plugin, if it's built in.

**Comment by johnalarcon** [comment]
Yes, that's correct: it's now built in and I've updated the Tiny config to reflect this. The code has not yet been uploaded.

**Comment by joyously** [comment]
This issue is closed, but not associated with a commit to remove the textcolor plugin folder.

**Comment by johnalarcon** [comment]
https://github.com/ClassicPress-research/ClassicPress-Editor/commit/24c053911867908b51cf2867b602f718de41de25

...that bootstrap file has been since removed.

**Comment by joyously** [comment]
That bootstrap file has nothing to do with the textcolor plugin folder. I'm saying that the folder should be deleted.

**Comment by joyously** [comment]
The `textcolor` folder has been deleted in b2f1fd1.
The `textcolor` plugin config parameter is removed in 947be91.
