### ISSUE TITLE
Implement plugin - wpview

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#51]
### Implement `wpview` TinyMCE plugin

The various controls and behaviors of the v4 plugin currently included in ClassicPress should be reasonably replicated by the v5 editor, or by the updated TinyMCE core. Prior to testing, install the [ClassicPress Editor](https://github.com/ClassicPress-research/ClassicPress-Editor/archive/refs/heads/main.zip) plugin. **Do not activate it.** If the plugin is already installed, be sure to deactivate it before starting your tests.

#### Testing Notes
```
Add testing notes here.
```

This issue has a corresponding item on the Task List in issue #2.

**Comment by joyously** [comment]
To test this plugin, click on a gallery in the editor. It should show a toolbar with two buttons: Edit and Remove.
The toolbar should remain visible if you scroll, as long as the gallery is visible.

In my testing, I was thinking the full height mode made it possible for the toolbar to be outside the editor iframe (overlapping the admin bar), but then it seemed to do it when I disabled full height mode. It seems that would be a problem with the context toolbars component, so the fix might be to go back to using the experimental floating toolbar that was being used before.

**Comment by joyously** [comment]
The calls to `addButton` are still 4.x. 
The 5.x contextToolbar seems to work correctly when not in fullheight mode, so any fix for that should be in the sizing code (wpautoresize or added function resizeTo), unless switching back to the experimental toolbar is needed.
Closing via 074e418
