### ISSUE TITLE
Visual and Text tabs are inconsistently styled

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#56]
**Describe the bug**
When clicking the tab for `Text` mode, the tab is made to look integrated with the section. When you click the `Visual` tab, a bottom border is preventing that same aesthetic.

#### Text mode
Active tab has no bottom border.
![image](https://user-images.githubusercontent.com/12477319/132929436-26aed841-aadf-4dcb-9eeb-1e3f7c6b60fa.png)

#### Visual mode
Active tab has bottom border.
![image](https://user-images.githubusercontent.com/12477319/132929678-6cfbc060-7392-49da-ad52-0b87cbc912c3.png)

**Comment by joyously** [comment]
It looks to me more like the toolbar has a border and it's on top instead of the visual button being on top.

**Comment by johnalarcon** [comment]
It could well be. I didn't investigate; just jotting down the issue before I forget. ;)
