### ISSUE TITLE
Use dividers to group editor buttons

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#57]
Use the built-in TinyMCE button dividers to create logical button groupings. This provides a visual distinction between the old and new editors and gives the new editor a more modern look.

---
#### Old editor 
![image](https://user-images.githubusercontent.com/12477319/132931773-f356c1c9-f568-4de3-9e04-57d7c54963df.png)

#### New editor
![image](https://user-images.githubusercontent.com/12477319/132931645-83a20d9b-ac3e-4a7e-9ffb-8aa3d5bf11bd.png)

#### New editor with dividers
![image](https://user-images.githubusercontent.com/12477319/132931418-36deb9da-beae-4a35-89ed-4e29510a1eb5.png)

**Comment by joyously** [comment]
I beg to differ on what is "modern".
The old days had lots of borders and lines. More recently, it's all minimalism.

This issue hasn't actually described the problem to solve though. It is just saying to do something for not a real reason.

**Comment by joyously** [comment]
> This all depends on how it is loaded. If it is a plugin then, yes, it should look different. Otherwise how do I know it's even working? If the plan is to include it in core then I have no problem with it looking exactly the same, as it will be a seamless change. Except you'll have a bunch of people saying "Huh... all that work for what?" :-)

_Originally posted by @simplycomputing in https://github.com/ClassicPress-research/ClassicPress-Editor/issues/9#issuecomment-917318448_

This plugin is just a test bed for changes that will go into core.
Everyone seemed to want the upgrade, regardless of how it looks.

**Comment by johnalarcon** [comment]
>This provides a visual distinction between the old and new editors...

...which is the same argument used for the undo/redo buttons.

**Comment by johnalarcon** [comment]
The dividers were [implemented](https://github.com/ClassicPress-research/ClassicPress-Editor/commit/b792409ce1e2e9f4221be651674f11af587b7aa7) while adding the Tiny config properties to the init method.
