### ISSUE TITLE
The "More..." button state is not persisted

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#6]
Clicking the "More..." button reveals another row of controls. The state (hidden/displayed) is not persisted across page loads.

![image](https://user-images.githubusercontent.com/12477319/131266526-16da7111-d982-4ed7-9e4b-344f0d7df7ff.png)

**Comment by arjayarana** [comment]
Speaking of MORE... there is no option to add the MORE tag `<!--more-->` that will break the post in the blog archive.

**Comment by johnalarcon** [comment]
> there is no option to add the MORE tag `<!--more-->`

Please start a new issue as that's a completely different feature/button.

**Comment by alvarofranz** [comment]
**Related docs**: [toolbar_mode ](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_mode)

I opened a GH issue on the tiny repo: [Persist the toolbar_mode open/hidden on the device](https://github.com/tinymce/tinymce/issues/7168)

**Comment by johnalarcon** [comment]
Thanks. A simple stopgap fix is to set `toolbar_mode: wrap` which removes the "More..." button altogether and displays all the groups/buttons.

**Comment by johnalarcon** [comment]
We've reconfigured the editor buttons/rows into a more real-world scenario. They will likely change again, however, it seems unlikely the GUI will ever have so many buttons that "More..." will show. Closing this as no longer an issue.
