### ISSUE TITLE
Inconsistent tooltip borders

### ISSUE THREAD

**Issue by viktorix** [ClassicPress-research/ClassicPress-Editor#69]
**Describe the bug**
Tooltip borders are inconsistent. Some tooltips miss one or more borders. As far as I can tell it's either bottom or right border that's missing.

**To Reproduce**
1. Hover over any editor buttons and wait for tooltip to show up.

**Expected behavior**
All 4 borders should be black and visible or implement v4 tooltips, which are black with white text.

**Screenshots**
![image](https://user-images.githubusercontent.com/1692600/136999613-65032e43-65dc-4a62-848c-502a61696626.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 94.0

**Comment by viktorix** [comment]
I believe the tooltips are default Chrome tooltips. In v4, I can pause script execution to inspect tooltips. I can't do that with v5. That's why styling isn't working.

**Comment by joyously** [comment]
In https://github.com/tinymce/tinymce/issues/7377#issuecomment-966056487
I was told that 5.x uses browser tooltips.
> TinyMCE 5 does not render custom tooltips, as TinyMCE 4 did. It only uses browser tooltips. Bringing back custom tooltips is something we initially planned to do, which is why tooltip.less was created when the release work began, but it was never implemented. The file is still unused. Sorry.
