### ISSUE TITLE
Where is the editor initialized?

### ISSUE THREAD

**Issue by alvarofranz** [ClassicPress-research/ClassicPress-Editor#75]
I am trying to find where the initializing point for all editors is. Is there any point where all editors go through before getting initialized?

I want to work on a feature to detect pasted images so that they get auto-uploaded to the media library, but I cannot find where the editor gets initialized. The closest place that would make sense is `wp.editor.initialize = function( id, settings ) { ... }`. But that function is neaver reached when opening "Posts -> Add new".

The idea is to attach a callback to the paste event in the editors settings.

**Comment by joyously** [comment]
This plugin is for updating the bundled editor from 4.x to 5.x. It's not for adding features to the editor.
To understand the initialization, you have to understand that TinyMCE has two modes. You also have to understand that core is PHP, and so it generates JS to run in the browser for the configuration, but also loads extra JS to handle the various things on the page that interact with the editor. 

For your question, you don't need to know the initialization, just need to write an editor plugin that handles paste and talks to the existing media handling code.

**Comment by alvarofranz** [comment]
Thanks @joyously - I know that the main scope is to update TinyMCE, but I like this feature and I want to try to make it happen. I will share my work so that it may be useful sometime.

So I added the plugin and I'm successfully detecting the paste event. Will keep on with it.

**Comment by alvarofranz** [comment]
So I actually got that working already. See the following screenshot:

![image](https://user-images.githubusercontent.com/83215112/139956531-6ec19586-5574-4b94-b81c-1e21f46079ea.png)

The image gets uploaded via AJAX and inserted into the editor. I have to work on making it secure but yeah. I'll start a petition on CP Forums to see who is interested.
