### ISSUE TITLE
Possible problem with multiple edit windows on one page

### ISSUE THREAD

**Issue by simplycomputing** [ClassicPress-research/ClassicPress-Editor#8]
When testing with Classic Commerce, the new editor applies on the top (long description) field. The short description field below reverts to a simple "text" mode.

![second-window](https://user-images.githubusercontent.com/46998578/131270744-035d5417-2835-4444-8900-5dbde5335cfd.jpg)

**Comment by johnalarcon** [comment]
So, what you're saying is: _it degrades gracefully_.

😄

**Comment by johnalarcon** [comment]
I'm not immediately finding the problem. This will require further investigation.

**Comment by simplycomputing** [comment]
This looks to be fixed now. Both data entry windows in Classic Commerce show the new editor.

**Comment by joyously** [comment]
Thanks for testing!
